//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cricket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlayer1
    {
        public int PlayerID { get; set; }
        public string PlayerName { get; set; }
        public Nullable<System.DateTime> PlayerDOB { get; set; }
        public string PlayerTeams { get; set; }
        public string PlayerBattingStyle { get; set; }
        public string PlayerBowlingStyle { get; set; }
        public string PlayerProfile { get; set; }
        public string PlayerRole { get; set; }
        public string PlayerMainTeam { get; set; }
        public string PlayerPhoto { get; set; }
    }
}
