//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cricket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTeam1
    {
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public string TeamPhoto { get; set; }
    }
}
